[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rawdlite-audio-doc"
authors = [{name = "Tom Roth", email = "rawdlite@gmail.com"}]
dynamic = ["version", "description"]
